{% set name = "ipyslurm" %}
{% set version = "1.1.0" %}
{% set hash = "385987e02e7537ce633f4b9893097c8207ffdf60edf9acc09872bfacf216c311" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=2.7
  run:
    - ipython
    - ipywidgets
    - notebook
    - paramiko
    - python >=2.7
    - six
    - tqdm

test:
  imports:
    - ipyslurm

about:
  home: https://auneri.github.io/ipyslurm
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'IPython extension for interacting with the Slurm Workload Manager from Jupyter notebook'

extra:
  recipe-maintainers:
    - auneri
