{% set name = "ipyslurm" %}
{% set version = "1.6.0" %}
{% set hash = "b6f35be39517da1b059a18980d306295e1a0d45ade94fc0ac8d7bd20e1a8596a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3
  run:
    - ipython >=7
    - ipywidgets >=7
    - notebook >=5
    - paramiko >=2.5
    - python >=3

test:
  imports:
    - ipyslurm

about:
  home: https://auneri.github.io/ipyslurm
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: IPython extension for interacting with the Slurm Workload Manager from Jupyter notebook

extra:
  recipe-maintainers:
    - auneri
