{% set name = "ipyslurm" %}
{% set version = "2.0.0" %}
{% set hash = "ada5ddccf6493e98c96add3d0949979cd584a7874b306b5e31abec1233d25820" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ipython >=7
    - ipywidgets >=7
    - paramiko >=2.5
    - python >=3.7
    - tqdm >=4

test:
  imports:
    - ipyslurm

about:
  home: https://auneri.github.io/ipyslurm
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: IPython extension for interacting with the Slurm Workload Manager from Jupyter notebook

extra:
  recipe-maintainers:
    - auneri
