{% set name = "ipyslurm" %}
{% set version = "1.3.0" %}
{% set hash = "79759f6eac4cbba0d95485b7afccabb9e886084442d7211519e08945545a1d57" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3
  run:
    - ipython >=7
    - ipywidgets >=7
    - notebook >=5
    - paramiko >=2
    - python >=3

test:
  imports:
    - ipyslurm

about:
  home: https://auneri.github.io/ipyslurm
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'IPython extension for interacting with the Slurm Workload Manager from Jupyter notebook'

extra:
  recipe-maintainers:
    - auneri
