travis:
  secure:
    BINSTAR_TOKEN: DKvcN/Wae+/xD05yGf0EmD3d3qI+gNxZY7rrNSmYxsfShD8IRZ8/cv56Av8UyK9iwLzxhpW1+aNC5ADqO+yEK5NJETEl+1jmLmonHuyGKt7aAAu0PnECHKvx3PJKRtA5/A2qlyt2L55v170lilXB7Zhyxsm/WXZTuuLeQeXyQjzxFH1yNCntj1658Zdl8hDsLl5t8+nPo2ADvTHwCLb+tPynTIQbhlRi+Ak9xnLG6BoRnjPqUVqvujYAGCBdjslHNJadiAh9ZbDJm3aYP4uE16zvpSsFYq8V/Ns1F6hNfHlV9EfWqv9eVEHXZaS8Iek42A9YaRTQuzW4aElYy93+Ywfqhm/EAiyo+avLbh7xzjG0jVAeLbGPmIFbCW4i2P37TtIwu6nIcqwGc/uttOyrwLPOXoPRMZkHl84g/WrsxdZ0z4Yihdl9GjmPT5OfrFeaUWrbkCKb95LLukGxv15q5+IEDMc4levzd7nDVhPO/W36MVgdGWysOKdMSDU82K+myvXWEl49yxk23Yp2RgdtUhygQotirMA0CT3FBk4SZ0In4dYz4KYnwuoD1BLcgHUN2oOjOFs431KhzLsAMmW7hSKgUVpaV3d6KzWf3hMjCvTNNKDnaWwbCZN6lrKDN5CNWGW16L+7/CL8dQd0u5uiydk3AsKHMUV2YVGK9Na4L8o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
