travis:
  secure:
    BINSTAR_TOKEN: ZrZWDFIcVEMEibdXESanr0k2T+1tCgKPfbo3BmONt60O2kkSU058I3/CU1s2ApjsqCbNw2PiD5OLTELGqCkyAYMMtLptb4gi0UtQs3is0hJuoY0C4wLtBvdhBam2EIKDw+f7qre8jmbVRJqUNjH+aVMnCuRe2ghPGzQ4Yc8YgIMKqE4ejauz46hgbRY4sy4RCIBLAAdViwYComNXNftIOolhYvW+ma6dZQUrnicx267D/U336PbVNhIGtvzbFJ5znP81gaNrBq5AhCcb1nqg2Toq7BgqhXa1a4re/sQz41XXz/aiRt+CEowFqqIztiknBJ/vrMlZ3FdC2e6l6egV7Cvo5xwhW+7wQdOqIT5tko9qm6L5A8jE4kPiYTqxdXuXYtTY9wxp18BcPivSorJsMlymkXrxqTG1Qma2KarDxoz6Ycyu1lcrNJpTS2CRcEN18eIf3L9efS5v6yEpcwZIZCyWsmLuysusFi21y+AozKcNkYMMAy0XxxUOCQNNB3UGwKEuLb8OUY3COMs6c8ScRPjpbnVwcGVbUj30AaTNBNw43TCyZMPanxgHcNOB036r8enW9ohDwltUQZ+lPL1JAJacG+lHHMQ1GX+do0EnbC0BlwXjDfv5tzouEtUHVFBF9DEtWmctznLhRADE6KrheWp1rh5PqL8DXs50UavTpSs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
